#cloud-config
# Construido sobre: https://cloudinit.readthedocs.io/en/latest/reference/base_config_reference.html#example
# Construido sobre: https://developer.hashicorp.com/terraform/tutorials/provision/cloud-init
# Construido sobre: https://www.digitalocean.com/community/tutorials/an-introduction-to-cloud-config-scripting

# Validado con: cloud-init schema --config-file vms/rpi-cloud-init.yml --annotate

groups:
  - docker

disable_root: true

users:
  - default
  - name: ubuntu
    doas:
      - permit nopass ubuntu
    lock_passwd: true
    gecos: Ubuntu
    groups: [adm, cdrom, dip, lxd, sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHW1wHywROx7wRU4yGiptulKbsas7swiPfCl+lk7vpPLZO1KW2hCGmgU/ASS8YzgZCUHEqj6LpBS+d+m/WXrJxZ0gEMQX1JIXhoPY2dWUx2AN+nVHyx4I7zP9e7IG3PY5x4o8x2ZuPz+PEduCOFerDT56cI2XtoEg5kuSb1EAg/DP5jqg== Llave MediSupply

timezone: America/Bogota

keyboard:
  layout: latam

# Unofficial distributions of Docker packages in APT; 
# No es perfecto, pero es una forma de instalar Docker en Ubuntu.
packages:
  - ufw
  - nginx
  - docker
  - docker.io
  - docker-compose-v2
  - python3-certbot-nginx
  - certbot
  - apache2-utils

runcmd:
  # 1. Levantar el servicio de Docker y la aplicacion de Gateway
  - [ systemctl, start, docker ]
  - [ systemctl, enable, docker ]
  - [ wget, "https://raw.githubusercontent.com/MateoC1098/MISW4501-Grupo8-MediSupply/main/IaC/docker/docker-compose.yml", -O, /home/ubuntu/docker-compose.yml ]
  - [ chown, ubuntu:docker, /home/ubuntu/docker-compose.yml ]
  - [ su, ubuntu, -c, "cd /home/ubuntu && docker compose up -d --build" ]
  # 2. Configurar el firewall
  - ufw reset 
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow in on lo
  - ufw allow from 127.0.0.1/8
  - ufw allow 'Nginx Full'
  - ufw allow 'OpenSSH'
  - ufw enable
