image: registry.gitlab.com/medisupply/infraestructura/ubuntu-for-deployments:latest

include:
  - local: "common-jobs.yml"

before_script:
  - cd IaC/configuration-management

stages:
  - preview
  - deploy

preview-puppet-medisupply:
  stage: preview
  variables:
    PORT: 22
    HOST: $MEDISUPPLY_GATEWAY_HOST
    KEY_TO_USE: "medisupply-key-ecdsa"
    DESIRED_PUPPET_MANIFEST: "site.pp"
  script:
    - !reference [.template-puppet-setup, script]
    - ssh -p "${PORT}" ubuntu@$HOST "(echo 'N'; echo 'N'; echo 'Y'; echo 'N';) | sudo ./main_work-machine.sh"
  resource_group: puppet-medisupply
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"

exec-puppet-medisupply:
  stage: deploy
  variables:
    PORT: 22
    HOST: $MEDISUPPLY_GATEWAY_HOST
    KEY_TO_USE: "medisupply-key-ecdsa"
    DESIRED_PUPPET_MANIFEST: "site.pp"
  script:
    - !reference [.template-puppet-setup, script]
    - ssh -p "${PORT}" ubuntu@$HOST "(echo 'N'; echo 'N'; echo 'N'; echo 'Y';) | sudo ./main_work-machine.sh"
  dependencies:
    - preview-puppet-medisupply
  resource_group: puppet-medisupply
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
  when: manual
