name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker-autenticacion:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant write permission for packages
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Api/autenticacion
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mateoc1098/misw4501-grupo8-medisupply/autenticacion:latest

  docker-gestion-perfiles:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant write permission for packages
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Api/gestion-perfiles
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mateoc1098/misw4501-grupo8-medisupply/gestion-perfiles:latest
